"""
paths.py — one place that decides where the livescore project's outputs live.

Everything generated by the speech-music project is sorted under outputs/:
    outputs/songs/         song-*.wav        (rendered keepsake audio)
    outputs/keepsakes/     keepsake-*.json   (captured tellings)
    outputs/arrangements/  arrangement-*.json (Audiotool-bound scores)
    outputs/telemetry/     telemetry-*.jsonl (live session logs)

Paths are ABSOLUTE (anchored to this file's directory), so they resolve the same
whether a module is imported or run as a script, and regardless of the caller's
working directory — important because app.py launches keepsake.py /
audiotool_arranger.py as subprocesses with cwd set to the project root.

The keepsake → song / keepsake → arrangement helpers preserve the original
timestamp (the prefix-swap the project has always used) while also moving the
result into the correct subfolder.
"""

from __future__ import annotations

import os

_BASE = os.path.dirname(os.path.abspath(__file__))
OUTPUTS = os.path.join(_BASE, "outputs")
SONGS = os.path.join(OUTPUTS, "songs")
KEEPSAKES = os.path.join(OUTPUTS, "keepsakes")
ARRANGEMENTS = os.path.join(OUTPUTS, "arrangements")
TELEMETRY = os.path.join(OUTPUTS, "telemetry")

for _d in (SONGS, KEEPSAKES, ARRANGEMENTS, TELEMETRY):
    os.makedirs(_d, exist_ok=True)


def keepsake_path(name: str) -> str:
    """Absolute path for a keepsake JSON (accepts a name or any path)."""
    return os.path.join(KEEPSAKES, os.path.basename(name))


def telemetry_path(name: str) -> str:
    return os.path.join(TELEMETRY, os.path.basename(name))


def song_for(keepsake: str) -> str:
    """song-<stamp>.wav in outputs/songs/, derived from a keepsake path."""
    b = os.path.basename(keepsake).replace("keepsake-", "song-").replace(".json", ".wav")
    return os.path.join(SONGS, b)


def arrangement_for(keepsake: str) -> str:
    """arrangement-<stamp>.json in outputs/arrangements/, from a keepsake path."""
    b = os.path.basename(keepsake)
    swapped = b.replace("keepsake-", "arrangement-")
    if swapped == b:                       # no prefix to swap
        swapped = b.replace(".json", ".arrangement.json")
    return os.path.join(ARRANGEMENTS, swapped)
